### ISSUE TITLE
How do I unsubscribe from this?

### ISSUE THREAD

**Issue by whitequark** [1egoman/backstroke#2]
I never requested getting unsolicited noise like this: https://github.com/whitequark/conda-build/pull/1

**Comment by 1egoman** [comment]
@whitequark I just added an optout feature: Within any of the pull requests backstroke generates. add a label called `optout`, then close it. Backstroke should not create any more pull requests within that repository. Let me know if this is sufficient.

If you'd like to disable backstroke completely (and added it yourself), just remove the webhook.

**Comment by whitequark** [comment]
That's rather irritating, since GitHub labels need to be added explicitly, and then it'll show up in the label dropdowns and such. I'll simply block the bot.

**Comment by 1egoman** [comment]
If you've got a better suggestion on how I should implement it, I'm willing to look at alternatives.

**Comment by whitequark** [comment]
Opt-in. Opt-out implies that many people will receive unsolicited issues.

**Comment by brentp** [comment]
I agree. Please do opt in. I contribute to a lot of projects and now get unwanted backstroke PRs. and closing the PR doesn't seem to help.

**Comment by 1egoman** [comment]
Let me explain why it's set up how it is.

Backstroke can be set up on either a fork or an upstream. If on a fork, it works just how you'd expect. When on an upstream, PRs are submitted to forks. I understand where you both are coming from--as someone who never accepted anything, the PRs are just spam. Backstroke as a tool is really for maintainers that want new users to not have to go through a ton of extra steps to pull in new changes. 

To answer your concerns, the package maintainer opted-in. They installed Backstroke into their repository to be helpful. If it isn't helpful for you, you can [specifically opt-out for that package for your fork only](https://github.com/1egoman/backstroke/blob/master/assets/disable-on-a-fork.md). It isn't a perfect solution, but it's the best one I have. Keep in mind that I built this for fun one week as a learning experience.

Hopefully that clarifies my intentions.

**Comment by cdhowie** [comment]
@1egoman Please do not take this personally, but there is absolutely no excuse for causing email noise to people who never asked for it.

I understand your reasoning, but you must also understand that I just sunk time into trying to figure out how to disable something that _I never enabled or opted in to_, which is sending me email and distracting me.  And that's after I have to figure out what is even going on, why these issues are being opened on a fork that I created so I could submit a single PR some time ago.

There has to be a middle ground.  For starters, the message left by the bot doesn't include any opt-out instructions.  The website it links to doesn't offer any such instructions either.  At least a lot of mailing list spam has the courtesy to include an opt-out link.

I resorted to simply blocking the bot from my whole account.

I do not doubt your good intentions.  However, you have unintentionally created a source of frustration and spam.  "Don't send unsolicited automated email" is Internet etiquette 101.
