### ISSUE TITLE
default setup not working (Error 500 on webhook)

### ISSUE THREAD

**Issue by eins78** [1egoman/backstroke#49]
I wanted to try out backstroke with a test repo, unfortunatly it is not working at all. I deleted and re-setup the Link several time with the same result.

According to github, and also when manually testing the hook via `curl` the webhook only responds with status 500 and `{"error":"Server error."}`

When I first set it up, I am sure that I saw a few "successfull" webhook pushes from github: the server response had a success message and showed the current number of forks, but no pull requests where sent (I shortly suspected it's a feature since they were all my own forks, but meanwhile other users have forked it as well but get no PRs).

repo in question: https://github.com/Madek/madek-instance

*Note:* the github username starts with an uppercase character, which is not very common. It might be an issue because github sometimes cares about the casing and sometimes not. Also the repo contains a git submodule, not sure if that could cause problems.

**Comment by 1egoman** [comment]
@eins78 I'd love to investigate this further. Could you give me the webhook logs so I can try to reproduce this? If you click on the webhook id, there are request headers and payload. Could you send me them? An example is posted below.

<img width="769" alt="screen shot 2017-01-17 at 5 24 28 pm" src="https://cloud.githubusercontent.com/assets/1704236/22042606/fb37293c-dcd9-11e6-9c66-7f50814ce47d.png">

**Comment by eins78** [comment]
@1egoman pasted here: https://gist.github.com/eins78/08e513d468b59ed3c5983cd91a09a181

**Comment by 1egoman** [comment]
@eins78 For now, would you mind switching to Backstroke classic? The simple way to do this is to update your webhook from `https://backstroke.us/_587e27bae78722001cf4e121` to `https://backstroke.us`.

I just manually ran it against the payload you gave me above using Backstroke Classic locally and it seemed to work. Here's one of the pull requests: https://github.com/eins78/street.ars.is/pull/2

**Comment by eins78** [comment]
@1egoman Ok, I made the webhook change, we'll see if it keeps working. Thanks for looking into it.
Note that this repo is not important and more or less just for playing around with backstroke, so if you want to debug further just tell me :)

**Comment by thtliife** [comment]
@eins78 I was getting that error if I had the web hook set to use x-url-encoding instead of application/json

**Comment by 1egoman** [comment]
Closing out of inactivity.
