### ISSUE TITLE
Setup when clone is not a GitHub Fork

### ISSUE THREAD

**Issue by torsknod** [1egoman/backstroke#55]
I have a "fork" of my own public repository as public repository (same GitHub account). As GitHub did not allow this, I just cloned it again, changed the remote master url to the "fork" repository and then added a upstream remote url.
Now backstroke does not accept this "fork", because it does not detect it as a fork.
There should be a checkbox to just merge whatever I want.

**Comment by 1egoman** [comment]
@torsknod Unfortunately, this is a Github limitation. If you take a look at https://developer.github.com/v3/pulls/#create-a-pull-request, Github only allows you to specify a pull request to a repository in the same network. There may be ways to get around a limitation like this, but for simplicities sake I'd prefer to not support that.

A potential solution could be to put one fork on your personal account, one on an organization that you own.
