### ISSUE TITLE
Cannot select master branch

### ISSUE THREAD

**Issue by johanneskoester** [1egoman/backstroke#56]
When trying to create a new link, I can't find the master branch in the list of branches. Further, the save button stays disabled. Am I missing something?

**Comment by 1egoman** [comment]
@johanneskoester Can you provide more information:

- What repositories are you trying to link?
- Can you provide a screenshot?
- If the save button is disabled, that means you either didn't give the link a name (`Biome` in the below example), or you didn't configure `From` or `To` correctly (if you didn't select a branch on one of the links, then you wouldn't be able to save).

<img width="1173" alt="screen shot 2017-03-10 at 6 02 06 am" src="https://cloud.githubusercontent.com/assets/1704236/23792967/268e84ae-0557-11e7-98dd-89abeeb3abc5.png">

**Comment by johanneskoester** [comment]
![backstroke-problem](https://cloud.githubusercontent.com/assets/1858646/23793995/4058a40a-058e-11e7-94e9-05cd459f98bb.png)

**Comment by johanneskoester** [comment]
I try to sync to all forks, but the problem is really that I cannot select the master branch. We have branch protection activated (disallowing pushes to master). Could that be the problem?

**Comment by 1egoman** [comment]
@johanneskoester Possibly. Let me give it a try on my end.

**Comment by 1egoman** [comment]
@johanneskoester 

I've tried a few different api calls:
- `curl https://api.github.com/repos/bioconda/bioconda-recipes/branches | grep master` - what backstroke does currently behind the scenes.
- `curl -H 'Content-Type: application/vnd.github.loki-preview+json' https://api.github.com/repos/bioconda/bioconda-recipes/branches?protected=true | grep master` - with the protected branch api which is in preview.

Neither of them seem to return your `master` branch. I have another repository of mine that I can't see the master branch on either, and the api returns similar results, and it doesn't use a protected branch, so I doubt that's the issue unfortunately.

A few things that you can do to help:
- Do either of the above commands return anything if you run them on your end?
- If you're willing to turn off branch protection temporarily and then give Backstroke a try that'd be a helpful datapoint. (You should be able to turn it back afterwards.)

**Comment by johanneskoester** [comment]
I just tried. Same results. Also, deactivating branch protection does not help.

**Comment by johanneskoester** [comment]
Maybe this is about paging? We have a lot of branches...

**Comment by johanneskoester** [comment]
Yes, that's it. If I add `?per_page=10000` I get the master branch. Maybe you don't properly walk through the pages in your implementation?

**Comment by 1egoman** [comment]
@johanneskoester That could be true. Let me take a look.

**Comment by 1egoman** [comment]
Yep, that's it. https://github.com/1egoman/backstroke/pull/57

**Comment by johanneskoester** [comment]
Thanks!

**Comment by 1egoman** [comment]
@johanneskoester The hotfix has been pushed, hopefully this solves your issue.

**Comment by johanneskoester** [comment]
Thanks!
