### ISSUE TITLE
How to automatically monitor all upstreams forks?

### ISSUE THREAD

**Issue by evandrocoan** [1egoman/backstroke#61]
The upstream of my fork can have several forks, as mime. I setup this to monitor the upstream, but I would like to know if any of the other forks also receives updates. 

This is very useful for Sublime Text packages because most packages developer went MIA (missing in action), so the pull requests on the upstream are always stalled. But their repositories forks are active and receive updates. For example: https://github.com/robertcollier4/REG/pull/2 

Related issue:

1. https://github.com/frost-nzcr4/find_forks/issues/8 How to find all other forks and the upstream from my fork?

**Comment by 1egoman** [comment]
@evandrocoan Only immediate forks (ie, forks one level below the upstream) are updated, because [Github's list all forks api call](https://developer.github.com/v3/repos/forks/) works this way.

**Comment by evandrocoan** [comment]
I am not saying to follow many levels, but all forks on the first level.
