### ISSUE TITLE
Error: This repo does not exits, for a fork of fork of fork fork of fork forked by me

### ISSUE THREAD

**Issue by evandrocoan** [1egoman/backstroke#69]
The repository https://github.com/Jayflux/sublime_toml_highlighting is a fork of fork of ... forked by me, and when I enter both these data I got:

![image](https://user-images.githubusercontent.com/5332158/30996068-5040a3fe-a494-11e7-990e-d5f77eab8e2b.png)

**Comment by evandrocoan** [comment]
Now I am having this error for every repository I try to put there.

**Comment by 1egoman** [comment]
Interesting - I never actually anticipated this case!

To get the branches for a given repository and to determine if the repository exists / doesn't exist, an api call is made. If you open up your browsers developer tools and look for that request, is the server returning an incorrect response? Though I suspect the server, as a first step, I'd like to see if the browser or the server is at fault.

Second, can you recreate this readily? I'd love to put together a couple scenarios in which the system currently doesn't work as expected.

Thanks!

**Comment by evandrocoan** [comment]
Now it is working by itself. It seems it stopped working exactly on the moment I tried to put the fork of fork. Now I added and it is working. Also, I am not experienced with web development, is this the console you mentioned? I took I picture now I it working:

![image](https://user-images.githubusercontent.com/5332158/30996687-f50e2772-a498-11e7-9289-b2de244e68e2.png)
